export const ptBr = {
  firstDayOfWeek: 1,
  dayNames: ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"],
  dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
  dayNamesMin: ["D", "S", "T", "Q", "Q", "S", "S"],
  monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
  monthNamesShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
  today: 'Hoje',
  clear: 'Limpar',
  startsWith: 'Começa com',
  contains: 'Contém',
  notContains: 'Não contém',
  endsWith: 'Termina com',
  equals: 'Igual',
  notEquals: 'Diferente',
  noFilter: 'Sem Filtro',
  filterPlaceholder: 'Pesquisar',
  accept: 'Aceitar',
  reject: 'Rejeitar',
  choose: 'Escolher',
  upload: 'Enviar',
  cancel: 'Cancelar',
  weekHeader: 'Sem',
  dateFormat: 'dd/mm/yy',
  weak: 'Fraco',
  medium: 'Médio',
  strong: 'Forte',
  passwordPrompt: 'Digite uma senha',
  emptyMessage: 'Nenhum resultado encontrado',
  emptyFilterMessage: 'Nenhum resultado encontrado',
  // PrimeReact Table
  chooseAll: 'Selecionar todos',
  unchooseAll: 'Desmarcar todos',
  close: 'Fechar',
  prev: 'Anterior',
  next: 'Próximo',
  rowsPerPage: 'Linhas por página',
  pageReport: 'Mostrando {first} a {last} de {totalRecords} registros',
  gotoPage: 'Ir para a página',
  mathAll: "Contem tudo",
  mathAny: "Contem qualquer um"
};
